---
version: "3.0"

services:
  package:
    image: natanfelles/package
    container_name: database-extra
    working_dir: /package
    volumes:
      - .:/package
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: framework-tests
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    container_name: database-extra-mariadb